add styling and linting configs
capmo/config pull request #1
Opened 2021-02-12 10:44 UTC by GregoryEDev

This is the first iteration of the Capmo Styling config:

We are all going to use this so please comment so that we can agree. This is currently a barebones config to avoid any preference and follow a standard that currently exists and is battle tested.

2021-02-12 12:44 UTC, kotielnikov approved these changes

2021-02-12 20:18 UTC, sebastian-schlecht approved these changes
I am happy with this, the only 'comment' I would have is to not have this in a sub-folder but directly in the repository root to make it work as a template.

2021-02-14 20:19 UTC, vahid-capmo commented on Linting and Styling/tsconfig.json
> +      // "emitDecoratorMetadata": true, /* Enables experimental support for emitting type metadata for decorators. */
We have this enabled on capmo repo

2021-02-14 20:32 UTC, vahid-capmo approved these changes
Good effort 👍

2021-02-14 20:32 UTC, vahid-capmo commented on Linting and Styling/tsconfig.json
> +      // "strictNullChecks": true, /* Enable strict null checks. */
This is enabled for capmo repo

2021-02-14 20:32 UTC, vahid-capmo commented on README.md
> +
Would be cool if we had a script to copy default config into a new project

2021-02-14 20:32 UTC, vahid-capmo commented on Linting and Styling/.prettierrc
> +  "semi": true,
👍

2021-02-15 08:00 UTC, GregoryEDev commented on Linting and Styling/.prettierrc
> +  "semi": true,
@vahid-capmo Do you like semi-colon?

2021-02-15 08:03 UTC, vahid-capmo commented on Linting and Styling/.prettierrc
> +  "semi": true,
yes actually I like to see them at the end of commands 😊

2021-02-15 08:05 UTC, GregoryEDev commented on Linting and Styling/.prettierrc
> +  "semi": true,
https://medium.com/@eugenkiss/dont-use-semicolons-in-typescript-474ccfe4bdb3

2021-02-15 08:10 UTC, GregoryEDev commented on README.md
> +
we could at a later stage turn it into a GitHub package

2021-02-15 08:11 UTC, GregoryEDev commented on Linting and Styling/tsconfig.json
> +      // "strictNullChecks": true, /* Enable strict null checks. */
We can then enable it within the Capmo repo, this is a barebones allowing for config in all projects.

2021-02-15 08:11 UTC, GregoryEDev commented on Linting and Styling/tsconfig.json
> +      // "emitDecoratorMetadata": true, /* Enables experimental support for emitting type metadata for decorators. */
We can then enable it within the Capmo repo, this is a barebones allowing for config in all projects.

2021-02-15 08:33 UTC, sebastian-schlecht commented on Linting and Styling/.prettierrc
> +  "semi": true,
I like **not** having a semi-colons tbh. I do find them useless too and it means less clutter and noise in the IDE.

2021-02-15 08:35 UTC, sebastian-schlecht commented on Linting and Styling/.prettierrc
> +  "semi": true,
the article, @GregoryEDev shared is quite nice imo

2021-02-15 08:39 UTC, sebastian-schlecht commented on Linting and Styling/tsconfig.eslint.json
> +    "exclude": ["node_modules", "test", "dist", "**/*spec.ts", "cdk", "cdk.out"]
maybe add `build`

2021-02-15 08:41 UTC, sebastian-schlecht commented on Linting and Styling/tsconfig.json
> +      // "noImplicitAny": true, /* Raise error on expressions and declarations with an implied 'any' type. */
why disabled?

2021-02-15 08:42 UTC, sebastian-schlecht commented on Linting and Styling/tsconfig.json
> +      // "strictNullChecks": true, /* Enable strict null checks. */
why disabled?

2021-02-15 08:42 UTC, sebastian-schlecht commented on Linting and Styling/tsconfig.json
> +      // "noImplicitReturns": true, /* Report error when not all code paths in function return a value. */
this should be on enabled, imo

2021-02-15 08:43 UTC, sebastian-schlecht commented on Linting and Styling/tsconfig.json
> +      // "noUnusedLocals": true, /* Report errors on unused locals. */
should be enabled imo. this is mostly not causing harm but why not just remove them?

2021-02-15 08:44 UTC, sebastian-schlecht commented on Linting and Styling/tsconfig.json
> +{
I'd opt to make this a notch _stricter_

2021-02-15 09:42 UTC, attilakiss323 approved these changes

2021-02-15 09:45 UTC, across-the-grid approved these changes

2021-02-15 09:53 UTC, GregoryEDev commented on Linting and Styling/tsconfig.json
> +      // "strictNullChecks": true, /* Enable strict null checks. */
Happy to enable, the rules are here for comment on what we do/do not enable

2021-02-15 09:55 UTC, GregoryEDev commented on Linting and Styling/tsconfig.json
> +      // "noImplicitAny": true, /* Raise error on expressions and declarations with an implied 'any' type. */
Will enable, no reason for it to be disabled

2021-02-15 09:57 UTC, GregoryEDev commented on Linting and Styling/tsconfig.json
> +{
Cool, I will enable a few of the checks that seem useful

2021-02-15 10:55 UTC, miodrage commented on Linting and Styling/.prettierrc
> +  "semi": true,
https://github.com/olliahonen/should-i-use-semicolons-ts

There are some cases when going without a semi-colon would cause issues, but they can be prevented with some linter rules. Find them here. https://github.com/olliahonen/should-i-use-semicolons-ts

2021-02-15 10:58 UTC, miodrage commented on Linting and Styling/.prettierrc
> +  "printWidth": 120
120 seems too much - 80 - 90 looks more compact.

2021-02-15 11:08 UTC, miodrage requested changes

2021-02-15 11:08 UTC, miodrage commented on Linting and Styling/.prettierrc
> +}
![image](https://user-images.githubusercontent.com/14963603/107938597-e9df6f80-6f85-11eb-8a1b-6d2c9b802ccd.png)

To true?

2021-02-15 11:08 UTC, miodrage commented on Linting and Styling/.prettierrc
> +}
![image](https://user-images.githubusercontent.com/14963603/107938772-21e6b280-6f86-11eb-9f0e-628b471c854a.png)

"none"?

2021-02-15 11:08 UTC, miodrage commented on README.md
> +This serves as a bsic configuration to standardise all our repositories. The styling makes use of the following technologies
Typo "bsic"

2021-02-15 11:28 UTC, miodrage commented
@GregoryEDev What about the codeclimate configuration? Could we add it now, or rather sometime later?

2021-02-15 11:30 UTC, vahid-capmo commented on Linting and Styling/.prettierrc
> +  "semi": true,
This is the code that I don't like to see
```
afterEach(() => {
    ;(middy as jest.Mock).mockClear()
    ;(httpErrorHandler as jest.Mock).mockClear()
    ;(httpEventNormalizer as jest.Mock).mockClear()
    ;(httpHeaderNormalizer as jest.Mock).mockClear()
    ;(validator as jest.Mock).mockClear()
    ;(log as jest.Mock).mockClear()
    ;(deleteByQuery as jest.Mock).mockClear()
  })
```
Semicolon in the beginning of the line, if we can somehow avoid it when not using semis, I'm fine with it 😄

2021-02-15 11:33 UTC, miodrage commented on Linting and Styling/.prettierrc
> +  "semi": true,
![image](https://user-images.githubusercontent.com/14963603/107941357-e4842400-6f89-11eb-8773-c3f60ba8e07a.png)
@vahid-capmo Let me unsee it 🤣

2021-02-15 11:51 UTC, GregoryEDev commented on Linting and Styling/.prettierrc
> +  "semi": true,
Ok cool, so we can disable and add the rule `"no-unexpected-multiline": true` to and have some coverage for these errors, we can then safely disable semis

2021-02-15 11:51 UTC, GregoryEDev commented on Linting and Styling/.prettierrc
> +  "printWidth": 120
I like 80

2021-02-15 11:56 UTC, vahid-capmo commented on Linting and Styling/.prettierrc
> +  "semi": true,
My personal preference it to keep them :)

![image](https://media.giphy.com/media/aZ4sQUpybai5y/giphy.gif)

2021-02-15 11:58 UTC, vahid-capmo commented on Linting and Styling/.prettierrc
> +  "semi": true,
Should we put this to vote on slack? 
@GregoryEDev @sebastian-schlecht

2021-02-15 12:03 UTC, sebastian-schlecht commented on Linting and Styling/.prettierrc
> +  "semi": true,
> Ok cool, so we can disable and add the rule `"no-unexpected-multiline": true` to and have some coverage for these errors, we can then safely disable semis

what Greg says 😄

2021-02-15 16:06 UTC, GregoryEDev commented
@miodrage Unfortunately this does not form part of linting/styling, we can create a separate PR for this and ensure everyone has ample time to comment on the config once we reach this part of our standards.

2021-02-15 16:11 UTC, miodrage approved these changes

2021-02-15 16:18 UTC, merged