[IES-410] Export linting config
capmo/config pull request #24
Opened 2021-05-03 14:59 UTC by theRossFromFriends

https://capmo-team.atlassian.net/browse/IES-410

PR aims to export linting config from the repository.

2021-05-03 16:12 UTC, theRossFromFriends commented on Linting and Styling/index.js
> +  prettierrc
Possibly we would put inside the `prettier` object also the prettierignore (the ticket description says 'place the ignore and RC under one file and export them both for easy access'), I am not sure however if it is possible.

2021-05-03 16:36 UTC, vahid-capmo requested changes
Can we consider separating eslint stuff from prettier stuff into their own folder? and folder name should not contain spaces

2021-05-03 16:40 UTC, vahid-capmo commented on Linting and Styling/eslintrc.js
> +const esLintrc = {
Can we rename it to better reflect it's purpose? like `eslintConfig`?

2021-05-03 16:41 UTC, vahid-capmo commented on Linting and Styling/index.js
> +  prettier, esLintrc
Can we make this repo use prettier to format the code inside it's own repo?

2021-05-03 16:41 UTC, vahid-capmo commented on Linting and Styling/prettierrc.js
> +const prettierrc = {
Can we rename it to `prettierConfig`?

2021-05-03 16:42 UTC, vahid-capmo commented on index.js
> +}
Could use new line

2021-05-04 09:33 UTC, GregoryEDev commented on Linting and Styling/index.js
> +  prettier, esLintrc
I have done this in my PR

2021-05-04 09:36 UTC, GregoryEDev commented on Linting and Styling/prettierrc.js
> +const prettierrc = {
```suggestion
const prettierConfig = {
```

2021-05-04 09:36 UTC, GregoryEDev commented on Linting and Styling/prettierrc.js
> +  prettierrc
```suggestion
  prettierConfig
```

2021-05-04 09:36 UTC, GregoryEDev commented on README.md
> +const { prettierrc } = require('@capmo/config/prettier');
```suggestion
const { prettierConfig } = require('@capmo/config/prettier');
```

2021-05-04 09:36 UTC, GregoryEDev commented on README.md
> +module.exports = { ...prettierrc };
```suggestion
module.exports = { ...prettierConfig };
```

2021-05-04 09:36 UTC, GregoryEDev commented on index.js
> +}
```suggestion
}

```

2021-05-04 09:36 UTC, GregoryEDev commented on Linting and Styling/index.js
> +const { prettierrc } = require('./prettierrc')
```suggestion
const { prettierConfig } = require('./prettierrc')
```

2021-05-04 09:36 UTC, GregoryEDev commented on Linting and Styling/index.js
> +  prettierrc
```suggestion
  prettierConfig
```

2021-05-04 09:36 UTC, GregoryEDev commented on Linting and Styling/eslintrc.js
> +const esLintrc = {
```suggestion
const eslintConfig = {
```

2021-05-04 09:36 UTC, GregoryEDev commented on Linting and Styling/eslintrc.js
> +  esLintrc
```suggestion
  eslintConfig
```

2021-05-04 09:36 UTC, GregoryEDev commented on Linting and Styling/index.js
> +const { esLintrc } = require('./eslintrc')
```suggestion
const { eslintConfig } = require('./eslintrc')
```

2021-05-04 09:36 UTC, GregoryEDev commented on Linting and Styling/index.js
> +  prettier, esLintrc
```suggestion
  prettier, eslintConfig
```

2021-05-04 09:36 UTC, GregoryEDev commented on README.md
> +const { esLintrc } = require('@capmo/config');
```suggestion
const { eslintConfig } = require('@capmo/config');
```

2021-05-04 09:36 UTC, GregoryEDev commented on README.md
> + ...esLintrc
```suggestion
 ...eslintConfig
```

2021-05-04 09:36 UTC, GregoryEDev commented on index.js
> + esLintrc,
```suggestion
 eslintConfig,
```

2021-05-04 09:36 UTC, GregoryEDev commented on index.js
> +import { esLintrc, prettier, }  from './linting_styling'
```suggestion
import { eslintConfig, prettier, }  from './linting_styling'
```

2021-05-04 09:38 UTC, GregoryEDev approved these changes

2021-05-04 09:43 UTC, vahid-capmo reviewed
What is your point of view on folder name `Linting and Styling`?
@GregoryEDev

2021-05-04 09:43 UTC, vahid-capmo commented on index.js
> +import { eslintConfig, prettier, }  from './linting_styling'
Unnecessary comma after prettier import

2021-05-04 09:43 UTC, vahid-capmo commented on README.md
> +const { prettierConfig } = require('@capmo/config/prettier');
Does this line actually work?

2021-05-04 10:03 UTC, GregoryEDev commented on index.js
> +import { eslintConfig, prettier, }  from './linting_styling'
```suggestion
import { eslintConfig, prettier }  from './linting_styling'
```

2021-05-04 10:06 UTC, GregoryEDev commented on Linting and Styling/index.js
> +}
```suggestion
const { prettierConfig } = require('./prettierrc')
const { eslintConfig } = require('./eslintrc')

module.exports = {
  prettierConfig, eslintConfig
}
```

2021-05-04 10:06 UTC, GregoryEDev commented on README.md
> +const { prettierConfig } = require('@capmo/config/prettier');
```suggestion
const { prettierConfig } = require('@capmo/config');
```

2021-05-04 10:14 UTC, vahid-capmo approved these changes

2021-05-04 10:17 UTC, merged